# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0005_auto_20171007_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Gender',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], help_text='Select your gender', max_length=1),
        ),
    ]
