# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 03:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Vote', '0006_student_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caditate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='College_Dean',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
