# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0007_auto_20171007_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caditate',
            name='user',
        ),
        migrations.DeleteModel(
            name='Caditate',
        ),
    ]
