# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 04:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0010_caditate_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Caditate',
            new_name='Cadidate',
        ),
    ]
