# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 04:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0013_auto_20171007_0427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='student',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='user',
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
    ]
