# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 04:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_auto_20171007_0440'),
        ('Vote', '0015_auto_20171007_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.Student'),
        ),
    ]
