# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 05:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0017_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='course',
            new_name='candidate',
        ),
    ]
