# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 05:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0021_candidate_party_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partylist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='party_list',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='position',
        ),
        migrations.AddField(
            model_name='position',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Position', to='Vote.Candidate'),
        ),
        migrations.DeleteModel(
            name='Partylist',
        ),
    ]
