# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 05:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Vote', '0022_auto_20171009_0514'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partylist_name', models.CharField(max_length=200)),
                ('goal', models.CharField(max_length=200)),
                ('projects', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='position',
            name='candidate',
        ),
        migrations.AddField(
            model_name='candidate',
            name='postion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Candidate', to='Vote.Position'),
        ),
    ]
