# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 00:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PartyList', '0002_partylist_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partylist',
            name='position',
        ),
    ]
