# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Position', '0007_remove_position_party_list'),
        ('PartyList', '0003_remove_partylist_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='partylist',
            name='position',
            field=models.ManyToManyField(related_name='PartyList', to='Position.Position'),
        ),
    ]
