# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PartyList', '0005_remove_partylist_position'),
        ('Position', '0007_remove_position_party_list'),
        ('Candidate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='party_list',
            field=models.ForeignKey(blank=True, null='True', on_delete=django.db.models.deletion.CASCADE, related_name='Candidate', to='PartyList.PartyList'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='position',
            field=models.ForeignKey(blank=True, null='True', on_delete=django.db.models.deletion.CASCADE, related_name='Candidate', to='Position.Position'),
        ),
    ]
