# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0003_law'),
    ]

    operations = [
        migrations.AddField(
            model_name='law',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
