# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidate', '0007_remove_candidate_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
