# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 08:38
from __future__ import unicode_literals

import Student.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_auto_20171009_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Gender',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], help_text='Select your gender', max_length=1, validators=[Student.validators.validate_gender]),
        ),
    ]
