# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 01:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0007_auto_20171009_0838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='FirstName',
            new_name='First_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='LastName',
            new_name='Last_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='MiddleName',
            new_name='Middle_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='birthday',
        ),
    ]
