# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 06:42
from __future__ import unicode_literals

import Student.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0008_auto_20171010_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.CharField(blank=True, choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year'), ('5', '5th Year')], help_text='Select your year', max_length=1, validators=[Student.validators.validate_gender]),
        ),
    ]
