# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 06:09
from __future__ import unicode_literals

import Student.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0013_auto_20171011_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(blank=True, choices=[('1', '1st year'), ('2', '2nd year'), ('3', '3rd year'), ('4', '4th year'), ('5', '5th year')], help_text='Select your year', max_length=1, validators=[Student.validators.validate_year]),
        ),
    ]
