# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Position', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
