# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 00:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PartyList', '0003_remove_partylist_position'),
        ('Position', '0002_auto_20171011_0844'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='party_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Position', to='PartyList.PartyList'),
        ),
    ]
