# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartyList', '0003_remove_partylist_position'),
        ('Position', '0004_remove_position_party_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='party_list',
            field=models.ManyToManyField(blank=True, null=True, related_name='Position', to='PartyList.PartyList'),
        ),
    ]
