# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 00:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Position', '0005_position_party_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='party_list',
            field=models.ManyToManyField(related_name='Position', to='PartyList.PartyList'),
        ),
    ]
