# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 00:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Position', '0006_auto_20171012_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='party_list',
        ),
    ]
